name: _button
description: Button Widget.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^1.1.6
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: